version: "3.9"
services:
  db_auth:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db_auth
  api_gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    links:
      - db_auth
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://root:root@hivesync_api-db_auth-1:5432/db_auth'
volumes:
  postgres_db:
