version: "3.9"
networks:
  hivesync_network:
    driver: bridge
services:
  db_auth:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${GATEWAY_DB_PORT}:5432
    volumes:
      - postgres_db_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_DB=${GATEWAY_DB_NAME}
    networks:
      - hivesync_network

  db_social:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${SOCIAL_DB_PORT}:5432
    volumes:
      - postgres_db_social:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_DB=${SOCIAL_DB_NAME}
    networks:
      - hivesync_network

  db_user:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${USER_DB_PORT}:5432
    volumes:
      - postgres_db_user:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}
    networks:
      - hivesync_network

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile.dev
    ports:
      - "${GATEWAY_SERVICE_PORT}:3000"
      - ${GATEWAY_PRISMA_PORT}:5555
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${DEFAULT_INTERNAL_PORT_API}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${GATEWAY_DB_HOST}:5432/${GATEWAY_DB_NAME}
    volumes:
      - ./api_gateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - hivesync_network

  social_service:
    build:
      context: ./social_service
      dockerfile: Dockerfile.dev
    ports:
      - "${SOCIAL_SERVICE_PORT}:3000"
      - ${SOCIAL_PRISMA_PORT}:5555
    environment:
      - PORT=${DEFAULT_INTERNAL_PORT_API}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${SOCIAL_DB_HOST}:5432/${SOCIAL_DB_NAME}
    volumes:
      - ./social_service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - hivesync_network
    
  user_info_service:
    build:
      context: ./user_info_service
      dockerfile: Dockerfile.dev
    ports:
      - "${USER_SERVICE_PORT}:3000"
      - ${USER_PRISMA_PORT}:5555
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${DEFAULT_INTERNAL_PORT_API}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${USER_DB_HOST}:5432/${USER_DB_NAME}
    volumes:
      - ./user_info_service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - hivesync_network

volumes:
  postgres_db_auth:
  postgres_db_social:
  postgres_db_user:
