version: "3.9"
services:
  db_auth:
    image: postgres:14-alpine
    ports:
      - 5432:${DB_PORT_AUTH}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_USER=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_AUTH}
  api_gateway:
    build: ./api_gateway
    ports:
      - "3000:${AUTH_SERVICE_PORT}"
    links:
      - db_auth
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST_AUTH}:${DB_PORT_AUTH}/${DB_NAME_AUTH}'
volumes:
  postgres_db:
